In [1]:
import sys
sys.path.append('C:\ironhack\Proyecto_final') # Hablar con el jefe
from src.help_datos import *
from src.help_scraping import *

In [2]:
url = 'https://rfevb-web.dataproject.com/Statistics.aspx?ID=59&PID=92'
parametro = 'estadistica_equipo'
dato=scraping(url,parametro)

hola
No se pudo hacer clic en el botón de cookies.
Scraping exitoso

In [13]:
columna = ['Equipo', 'Jugados', 'Sets_Jugados', 'Total_Puntos', 'Break_Puntos', 'Puntos_Ganados',
            'Puntos_Perdidos', 'Total_Saque', 'Puntos_Saque', 'Error_Saque', 'Puntos_por_set_Saque',
            'Efic_Saque', 'Total_Recepcion', 'Error_Recepcion', 'Negativo_Recepcion', 'Positivo_Recepcion',
            'Excelente_Recepcion', 'Efic_Recepcion', 'Total_Ataque', 'Error_Ataque', 'Ataque_Bloqueado',
            'Positivo_Ataque', 'Excelente_Ataque', 'Efic_Ataque', 'Toque_Red_Bloqueo', 'Puntos_de_Bloqueo',
            'Puntos_Set_Bloqueo']

parametro = 'estadistica'
estadistica=crear_df(dato,columna,parametro)

In [14]:
mapear_nombres(estadistica)

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Efic_Recepcion,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo
0,Arenal Emevé,20,78,1237,462,775,500,1722,97,255,...,41.0,2079,213,186,963,46.0,27.0,41,177,2.3
1,CV Teruel,20,71,1236,492,744,654,1677,102,274,...,29.0,1732,137,101,918,53.0,39.0,90,216,3.0
2,Vecindario Las Palmas,20,79,1229,473,756,527,1799,87,261,...,23.0,1961,178,169,927,47.0,30.0,98,215,2.7
3,Unicaja Almería,20,73,1221,527,694,686,1738,107,237,...,30.0,1747,109,116,908,52.0,39.0,262,206,2.8
4,Voley Palma,20,72,1205,472,733,557,1669,92,282,...,30.0,1866,131,153,904,48.0,33.0,97,209,2.9
5,Manacor,20,80,1195,417,778,383,1671,120,276,...,30.0,1997,199,206,913,46.0,25.0,138,162,2.0
6,Rio Duero Soria,20,75,1174,428,746,422,1631,96,274,...,35.0,1905,200,191,873,46.0,25.0,242,205,2.7
7,Grau,20,76,1169,417,752,557,1729,68,210,...,29.0,2245,158,170,932,42.0,27.0,219,169,2.2
8,Ibiza Voley,20,71,1165,444,721,485,1621,115,269,...,27.0,1869,153,176,898,48.0,30.0,229,152,2.1
9,Voley Textil Santanderina,20,75,1109,385,724,325,1606,101,286,...,25.0,1917,199,201,855,45.0,24.0,166,153,2.0
10,Voleibol Almoradí,20,77,1095,366,729,286,1610,84,273,...,23.0,2045,180,237,872,43.0,22.0,227,139,1.8
11,CV Melilla,20,71,947,268,679,182,1407,59,259,...,15.0,1840,178,204,779,42.0,22.0,125,109,1.5

In [15]:
normalizar_df(estadistica)

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Efic_Recepcion,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo
0,Arenal Emeve,20,78,1237,462,775,500,1722,97,255,...,41.0,2079,213,186,963,46.0,27.0,41,177,2.3
1,CV Teruel,20,71,1236,492,744,654,1677,102,274,...,29.0,1732,137,101,918,53.0,39.0,90,216,3.0
2,Vecindario Las Palmas,20,79,1229,473,756,527,1799,87,261,...,23.0,1961,178,169,927,47.0,30.0,98,215,2.7
3,Unicaja Almeria,20,73,1221,527,694,686,1738,107,237,...,30.0,1747,109,116,908,52.0,39.0,262,206,2.8
4,Voley Palma,20,72,1205,472,733,557,1669,92,282,...,30.0,1866,131,153,904,48.0,33.0,97,209,2.9
5,Manacor,20,80,1195,417,778,383,1671,120,276,...,30.0,1997,199,206,913,46.0,25.0,138,162,2.0
6,Rio Duero Soria,20,75,1174,428,746,422,1631,96,274,...,35.0,1905,200,191,873,46.0,25.0,242,205,2.7
7,Grau,20,76,1169,417,752,557,1729,68,210,...,29.0,2245,158,170,932,42.0,27.0,219,169,2.2
8,Ibiza Voley,20,71,1165,444,721,485,1621,115,269,...,27.0,1869,153,176,898,48.0,30.0,229,152,2.1
9,Voley Textil Santanderina,20,75,1109,385,724,325,1606,101,286,...,25.0,1917,199,201,855,45.0,24.0,166,153,2.0
10,Voleibol Almoradi,20,77,1095,366,729,286,1610,84,273,...,23.0,2045,180,237,872,43.0,22.0,227,139,1.8
11,CV Melilla,20,71,947,268,679,182,1407,59,259,...,15.0,1840,178,204,779,42.0,22.0,125,109,1.5

In [16]:
#Extraccion de jugadores.
df= pd.read_csv('../../data/2019-2020/equipo.csv')
df

                       Equipo     id_equipo
0                Arenal Emeve   1-2019-2020
1                   CV Teruel   2-2019-2020
2                     Manacor   3-2019-2020
3                  CV Melilla   4-2019-2020
4             Rio Duero Soria   5-2019-2020
5                        Grau   6-2019-2020
6             Unicaja Almeria   7-2019-2020
7                 Voley Palma   8-2019-2020
8                 Ibiza Voley   9-2019-2020
9       Vecindario Las Palmas  10-2019-2020
10          Voleibol Almoradi  11-2019-2020
11  Voley Textil Santanderina  12-2019-2020

In [17]:
estadistica = pd.merge(estadistica, df[['Equipo', 'id_equipo']], left_on='Equipo', right_on='Equipo', how='left')
estadistica['temporada']='2019-2020'
estadistica.head()

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo,id_equipo,temporada
0,Arenal Emeve,20,78,1237,462,775,500,1722,97,255,...,213,186,963,46.0,27.0,41,177,2.3,1-2019-2020,2019-2020
1,CV Teruel,20,71,1236,492,744,654,1677,102,274,...,137,101,918,53.0,39.0,90,216,3.0,2-2019-2020,2019-2020
2,Vecindario Las Palmas,20,79,1229,473,756,527,1799,87,261,...,178,169,927,47.0,30.0,98,215,2.7,10-2019-2020,2019-2020
3,Unicaja Almeria,20,73,1221,527,694,686,1738,107,237,...,109,116,908,52.0,39.0,262,206,2.8,7-2019-2020,2019-2020
4,Voley Palma,20,72,1205,472,733,557,1669,92,282,...,131,153,904,48.0,33.0,97,209,2.9,8-2019-2020,2019-2020

In [18]:
estadistica.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Equipo                12 non-null     object
 1   Jugados               12 non-null     int64
 2   Sets_Jugados          12 non-null     int64
 3   Total_Puntos          12 non-null     int64
 4   Break_Puntos          12 non-null     int64
 5   Puntos_Ganados        12 non-null     int64
 6   Puntos_Perdidos       12 non-null     int64
 7   Total_Saque           12 non-null     int64
 8   Puntos_Saque          12 non-null     int64
 9   Error_Saque           12 non-null     int64
 10  Puntos_por_set_Saque  12 non-null     float64
 11  Efic_Saque            12 non-null     float64
 12  Total_Recepcion       12 non-null     int64
 13  Error_Recepcion       12 non-null     int64
 14  Negativo_Recepcion    12 non-null     int64
 15  Positivo_Recepcion    12 non-null     int64
 16  Excelente_Recepcion   12 non-null     float64
 17  Efic_Recepcion        12 non-null     float64
 18  Total_Ataque          12 non-null     int64
 19  Error_Ataque          12 non-null     int64
 20  Ataque_Bloqueado      12 non-null     int64
 21  Positivo_Ataque       12 non-null     int64
 22  Excelente_Ataque      12 non-null     float64
 23  Efic_Ataque           12 non-null     float64
 24  Toque_Red_Bloqueo     12 non-null     int64
 25  Puntos_de_Bloqueo     12 non-null     int64
 26  Puntos_Set_Bloqueo    12 non-null     float64
 27  id_equipo             12 non-null     object
 28  temporada             12 non-null     object
dtypes: float64(7), int64(19), object(3)
memory usage: 2.8+ KB

## Guardado en CSV.

In [19]:
estadistica.to_csv('../../data/2019-2020/estadistica.csv', index=False)

## Base de datos.

In [10]:
with open('../../pass.txt', 'r') as file:   # pass.txt en .gitignore
    
    pass_ = file.read()

In [11]:
str_conn = f'mysql+pymysql://root:{pass_}@localhost:3306/'
conn = create_engine(str_conn)
engine = create_engine(f'mysql+pymysql://root:{pass_}@localhost:3306/volleyballdb')

In [13]:

estadistica.to_sql('estadistica', engine, if_exists='append', index=False)

12