In [2]:
import sys
sys.path.append('C:\ironhack\Proyecto_final') # Hablar con el jefe
from src.help_datos import *
from src.help_scraping import *

In [2]:
url = 'https://rfevb-web.dataproject.com/Statistics.aspx?ID=124&PID=152'
parametro = 'estadistica_equipo'
dato=scraping(url,parametro)

hola
No se pudo hacer clic en el botón de cookies.
Scraping exitoso

In [3]:
columna = ['Equipo', 'Jugados', 'Sets_Jugados', 'Total_Puntos', 'Break_Puntos', 'Puntos_Ganados',
            'Puntos_Perdidos', 'Total_Saque', 'Puntos_Saque', 'Error_Saque', 'Puntos_por_set_Saque',
            'Efic_Saque', 'Total_Recepcion', 'Error_Recepcion', 'Negativo_Recepcion', 'Positivo_Recepcion',
            'Excelente_Recepcion', 'Efic_Recepcion', 'Total_Ataque', 'Error_Ataque', 'Ataque_Bloqueado',
            'Positivo_Ataque', 'Excelente_Ataque', 'Efic_Ataque', 'Toque_Red_Bloqueo', 'Puntos_de_Bloqueo',
            'Puntos_Set_Bloqueo']

parametro = 'estadistica'
estadistica=crear_df(dato,columna,parametro)

In [4]:
mapear_nombres(estadistica)

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Efic_Recepcion,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo
0,Rio Duero Soria,9,35,608,226,382,311,821,37,129,...,21.0,997,63,61,480,48.0,36.0,157,91,2.6
1,Voley Palma,9,37,576,206,370,230,790,41,112,...,23.0,1053,103,84,464,44.0,26.0,88,71,1.9
2,CV San Roque,9,38,572,190,382,201,803,34,144,...,25.0,965,90,74,458,47.0,30.0,77,80,2.1
3,Conqueridor Valencia,9,37,568,210,358,229,789,53,109,...,13.0,1011,96,79,453,45.0,27.0,155,62,1.7
4,Cisneros Alter,9,35,547,170,377,226,777,32,143,...,32.0,893,86,66,446,50.0,33.0,28,69,2.0
5,Arenal Emevé,9,33,514,155,359,161,680,26,126,...,27.0,935,99,85,419,45.0,25.0,55,69,2.1
6,Guaguas,9,32,511,221,290,248,745,53,112,...,29.0,765,59,55,379,50.0,35.0,81,79,2.5
7,Unicaja Almería,9,29,511,211,300,279,699,56,112,...,25.0,692,41,50,392,57.0,43.0,106,63,2.2
8,CV Teruel,9,34,510,170,340,202,734,20,122,...,23.0,892,81,77,398,45.0,27.0,107,92,2.7
9,CV Melilla,9,31,510,183,327,232,730,42,119,...,37.0,847,54,68,406,48.0,34.0,80,62,2.0
10,Manacor,9,31,496,180,316,227,687,51,94,...,28.0,791,64,66,377,48.0,31.0,65,68,2.2
11,CV Villena Petrer,9,32,451,130,321,139,686,20,119,...,32.0,900,72,87,385,43.0,25.0,52,46,1.4

In [5]:
#Extraccion de jugadores.
df= pd.read_csv('../../../data/2023-2024/Equipos.csv')
df

                  Equipo     id_equipo
0           Arenal Emevé   1-2023-2024
1         Cisneros Alter   2-2023-2024
2            Voley Palma   3-2023-2024
3                Manacor   4-2023-2024
4                Guaguas   5-2023-2024
5             CV Melilla   6-2023-2024
6           CV San Roque   7-2023-2024
7        Rio Duero Soria   8-2023-2024
8              CV Teruel   9-2023-2024
9        Unicaja Almería  10-2023-2024
10  Conqueridor Valencia  11-2023-2024
11     CV Villena Petrer  12-2023-2024

In [7]:
result = pd.merge(estadistica, df[['Equipo', 'id_equipo']], left_on='Equipo', right_on='Equipo', how='left')
result['temporada']='2023-2024'
result.head(2)

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo,id_equipo
0,Rio Duero Soria,9,35,608,226,382,311,821,37,129,...,997,63,61,480,48.0,36.0,157,91,2.6,8-2023-2024
1,Voley Palma,9,37,576,206,370,230,790,41,112,...,1053,103,84,464,44.0,26.0,88,71,1.9,3-2023-2024
2,CV San Roque,9,38,572,190,382,201,803,34,144,...,965,90,74,458,47.0,30.0,77,80,2.1,7-2023-2024
3,Conqueridor Valencia,9,37,568,210,358,229,789,53,109,...,1011,96,79,453,45.0,27.0,155,62,1.7,11-2023-2024
4,Cisneros Alter,9,35,547,170,377,226,777,32,143,...,893,86,66,446,50.0,33.0,28,69,2.0,2-2023-2024

In [3]:
normalizar('../../../data/2023-2024/estadistica.csv')

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo,id_equipo,temporada
0,Rio Duero Soria,9,35,608,226,382,311,821,37,129,...,63,61,480,48.0,36.0,157,91,2.6,8-2023-2024,2023-2024
1,Voley Palma,9,37,576,206,370,230,790,41,112,...,103,84,464,44.0,26.0,88,71,1.9,3-2023-2024,2023-2024
2,CV San Roque,9,38,572,190,382,201,803,34,144,...,90,74,458,47.0,30.0,77,80,2.1,7-2023-2024,2023-2024
3,Conqueridor Valencia,9,37,568,210,358,229,789,53,109,...,96,79,453,45.0,27.0,155,62,1.7,11-2023-2024,2023-2024
4,Cisneros Alter,9,35,547,170,377,226,777,32,143,...,86,66,446,50.0,33.0,28,69,2.0,2-2023-2024,2023-2024
5,Arenal Emeve,9,33,514,155,359,161,680,26,126,...,99,85,419,45.0,25.0,55,69,2.1,1-2023-2024,2023-2024
6,Guaguas,9,32,511,221,290,248,745,53,112,...,59,55,379,50.0,35.0,81,79,2.5,5-2023-2024,2023-2024
7,Unicaja Almeria,9,29,511,211,300,279,699,56,112,...,41,50,392,57.0,43.0,106,63,2.2,10-2023-2024,2023-2024
8,CV Teruel,9,34,510,170,340,202,734,20,122,...,81,77,398,45.0,27.0,107,92,2.7,9-2023-2024,2023-2024
9,CV Melilla,9,31,510,183,327,232,730,42,119,...,54,68,406,48.0,34.0,80,62,2.0,6-2023-2024,2023-2024
10,Manacor,9,31,496,180,316,227,687,51,94,...,64,66,377,48.0,31.0,65,68,2.2,4-2023-2024,2023-2024
11,CV Villena Petrer,9,32,451,130,321,139,686,20,119,...,72,87,385,43.0,25.0,52,46,1.4,12-2023-2024,2023-2024

## Guardado en CSV.

In [7]:
estadistica.to_csv('../../../data/2023-2024/estadistica.csv', index=False)

## Base de datos.

In [8]:
with open('../../../pass.txt', 'r') as file:   # pass.txt en .gitignore
    
    pass_ = file.read()

In [9]:
str_conn = f'mysql+pymysql://root:{pass_}@localhost:3306/'
conn = create_engine(str_conn)
engine = create_engine(f'mysql+pymysql://root:{pass_}@localhost:3306/volleyballdb')

In [10]:
key = 'id_equipo'
dtype = {key: Integer}
estadistica.to_sql('estadistica', engine, if_exists='append', index=False)

12