In [1]:
import sys
sys.path.append('C:\ironhack\Proyecto_final') # Hablar con el jefe
from src.help_datos import *
from src.help_scraping import *

In [2]:
url = 'https://rfevb-web.dataproject.com/Statistics.aspx?ID=111&PID=137'
parametro = 'estadistica_equipo'
dato=scraping(url,parametro)

hola
No se pudo hacer clic en el botón de cookies.
Scraping exitoso

In [16]:
columna = ['Equipo', 'Jugados', 'Sets_Jugados', 'Total_Puntos', 'Break_Puntos', 'Puntos_Ganados',
            'Puntos_Perdidos', 'Total_Saque', 'Puntos_Saque', 'Error_Saque', 'Puntos_por_set_Saque',
            'Efic_Saque', 'Total_Recepcion', 'Error_Recepcion', 'Negativo_Recepcion', 'Positivo_Recepcion',
            'Excelente_Recepcion', 'Efic_Recepcion', 'Total_Ataque', 'Error_Ataque', 'Ataque_Bloqueado',
            'Positivo_Ataque', 'Excelente_Ataque', 'Efic_Ataque', 'Toque_Red_Bloqueo', 'Puntos_de_Bloqueo',
            'Puntos_Set_Bloqueo']

parametro = 'estadistica'
estadistica=crear_df(dato,columna,parametro)

In [17]:
mapear_nombres(estadistica)

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Efic_Recepcion,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo
0,Rio Duero Soria,30,109,1752,671,1081,669,2526,156,489,...,28.0,2852,232,239,1353,47.0,31.0,377,243,2.2
1,Guaguas,29,97,1735,781,954,965,2366,177,355,...,29.0,2424,173,164,1312,54.0,40.0,297,248,2.6
2,CV Teruel,28,102,1635,615,1020,763,2360,111,376,...,21.0,2577,208,179,1252,49.0,34.0,413,272,2.7
3,CV Melilla,27,96,1570,613,957,679,2230,115,351,...,31.0,2537,216,205,1191,47.0,30.0,344,264,2.8
4,Conqueridor Valencia,25,94,1539,566,973,628,2130,129,328,...,24.0,2597,237,234,1196,46.0,28.0,328,214,2.3
5,Unicaja Almería,25,91,1438,558,880,557,2064,128,362,...,24.0,2362,199,217,1053,45.0,27.0,386,257,2.8
6,Arenal Emevé,24,86,1310,442,868,449,1854,95,260,...,22.0,2402,246,237,1057,44.0,24.0,152,158,1.8
7,Barça Voleibol,24,84,1294,457,837,434,1874,116,381,...,26.0,2093,182,167,998,48.0,31.0,187,180,2.1
8,Voley Palma,22,83,1239,390,849,365,1790,76,291,...,26.0,2382,223,250,1001,42.0,22.0,101,162,2.0
9,Manacor,22,77,1201,447,754,476,1701,107,245,...,30.0,2038,167,189,906,44.0,27.0,148,188,2.4
10,Voley Textil Santanderina,22,75,1010,307,703,297,1488,70,202,...,24.0,2044,237,159,788,39.0,19.0,216,152,2.0
11,Rotogal Boiro,22,72,910,276,634,92,1390,69,239,...,29.0,1942,242,221,718,37.0,13.0,69,123,1.7

In [4]:
#Extraccion de jugadores.
df= pd.read_csv('../../data/2022-2023/Equipo.csv')
df

                       Equipo     id_equipo
0                Arenal Emeve   1-2022-2023
1              Barca Voleibol   2-2022-2023
2                 Voley Palma   3-2022-2023
3                     Manacor   4-2022-2023
4                     Guaguas   5-2022-2023
5        Conqueridor Valencia   6-2022-2023
6                  CV Melilla   7-2022-2023
7                   CV Teruel   8-2022-2023
8             Rio Duero Soria   9-2022-2023
9               Rotogal Boiro  10-2022-2023
10            Unicaja Almeria  11-2022-2023
11  Voley Textil Santanderina  12-2022-2023

In [8]:
estadistica= pd.read_csv('../../data/2022-2023/estadistica.csv')
estadistica

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Efic_Recepcion,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo
0,Rio Duero Soria,30,109,1752,671,1081,669,2526,156,489,...,28.0,2852,232,239,1353,47.0,31.0,377,243,2.2
1,Guaguas,29,97,1735,781,954,965,2366,177,355,...,29.0,2424,173,164,1312,54.0,40.0,297,248,2.6
2,CV Teruel,28,102,1635,615,1020,763,2360,111,376,...,21.0,2577,208,179,1252,49.0,34.0,413,272,2.7
3,CV Melilla,27,96,1570,613,957,679,2230,115,351,...,31.0,2537,216,205,1191,47.0,30.0,344,264,2.8
4,Conqueridor Valencia,25,94,1539,566,973,628,2130,129,328,...,24.0,2597,237,234,1196,46.0,28.0,328,214,2.3
5,Unicaja Almeria,25,91,1438,558,880,557,2064,128,362,...,24.0,2362,199,217,1053,45.0,27.0,386,257,2.8
6,Arenal Emeve,24,86,1310,442,868,449,1854,95,260,...,22.0,2402,246,237,1057,44.0,24.0,152,158,1.8
7,Barca Voleibol,24,84,1294,457,837,434,1874,116,381,...,26.0,2093,182,167,998,48.0,31.0,187,180,2.1
8,Voley Palma,22,83,1239,390,849,365,1790,76,291,...,26.0,2382,223,250,1001,42.0,22.0,101,162,2.0
9,Manacor,22,77,1201,447,754,476,1701,107,245,...,30.0,2038,167,189,906,44.0,27.0,148,188,2.4
10,Voley Textil Santanderina,22,75,1010,307,703,297,1488,70,202,...,24.0,2044,237,159,788,39.0,19.0,216,152,2.0
11,Rotogal Boiro,22,72,910,276,634,92,1390,69,239,...,29.0,1942,242,221,718,37.0,13.0,69,123,1.7

In [14]:
result = pd.merge(estadistica, df[['Equipo', 'id_equipo']], left_on='Equipo', right_on='Equipo', how='left')
result['temporada']='2022-2023'
result.head(2)

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo,id_equipo,temporada
0,Rio Duero Soria,30,109,1752,671,1081,669,2526,156,489,...,232,239,1353,47.0,31.0,377,243,2.2,9-2022-2023,2022-2023
1,Guaguas,29,97,1735,781,954,965,2366,177,355,...,173,164,1312,54.0,40.0,297,248,2.6,5-2022-2023,2022-2023

In [15]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Equipo                12 non-null     object
 1   Jugados               12 non-null     int64
 2   Sets_Jugados          12 non-null     int64
 3   Total_Puntos          12 non-null     int64
 4   Break_Puntos          12 non-null     int64
 5   Puntos_Ganados        12 non-null     int64
 6   Puntos_Perdidos       12 non-null     int64
 7   Total_Saque           12 non-null     int64
 8   Puntos_Saque          12 non-null     int64
 9   Error_Saque           12 non-null     int64
 10  Puntos_por_set_Saque  12 non-null     float64
 11  Efic_Saque            12 non-null     float64
 12  Total_Recepcion       12 non-null     int64
 13  Error_Recepcion       12 non-null     int64
 14  Negativo_Recepcion    12 non-null     int64
 15  Positivo_Recepcion    12 non-null     int64
 16  Excelente_Recepcion   12 non-null     float64
 17  Efic_Recepcion        12 non-null     float64
 18  Total_Ataque          12 non-null     int64
 19  Error_Ataque          12 non-null     int64
 20  Ataque_Bloqueado      12 non-null     int64
 21  Positivo_Ataque       12 non-null     int64
 22  Excelente_Ataque      12 non-null     float64
 23  Efic_Ataque           12 non-null     float64
 24  Toque_Red_Bloqueo     12 non-null     int64
 25  Puntos_de_Bloqueo     12 non-null     int64
 26  Puntos_Set_Bloqueo    12 non-null     float64
 27  id_equipo             12 non-null     object
 28  temporada             12 non-null     object
dtypes: float64(7), int64(19), object(3)
memory usage: 2.8+ KB

In [13]:
result=normalizar('../../data/2022-2023/estadistica.csv')
result

,Equipo,Jugados,Sets_Jugados,Total_Puntos,Break_Puntos,Puntos_Ganados,Puntos_Perdidos,Total_Saque,Puntos_Saque,Error_Saque,...,Efic_Recepcion,Total_Ataque,Error_Ataque,Ataque_Bloqueado,Positivo_Ataque,Excelente_Ataque,Efic_Ataque,Toque_Red_Bloqueo,Puntos_de_Bloqueo,Puntos_Set_Bloqueo
0,Rio Duero Soria,30,109,1752,671,1081,669,2526,156,489,...,28.0,2852,232,239,1353,47.0,31.0,377,243,2.2
1,Guaguas,29,97,1735,781,954,965,2366,177,355,...,29.0,2424,173,164,1312,54.0,40.0,297,248,2.6
2,CV Teruel,28,102,1635,615,1020,763,2360,111,376,...,21.0,2577,208,179,1252,49.0,34.0,413,272,2.7
3,CV Melilla,27,96,1570,613,957,679,2230,115,351,...,31.0,2537,216,205,1191,47.0,30.0,344,264,2.8
4,Conqueridor Valencia,25,94,1539,566,973,628,2130,129,328,...,24.0,2597,237,234,1196,46.0,28.0,328,214,2.3
5,Unicaja Almeria,25,91,1438,558,880,557,2064,128,362,...,24.0,2362,199,217,1053,45.0,27.0,386,257,2.8
6,Arenal Emeve,24,86,1310,442,868,449,1854,95,260,...,22.0,2402,246,237,1057,44.0,24.0,152,158,1.8
7,Barca Voleibol,24,84,1294,457,837,434,1874,116,381,...,26.0,2093,182,167,998,48.0,31.0,187,180,2.1
8,Voley Palma,22,83,1239,390,849,365,1790,76,291,...,26.0,2382,223,250,1001,42.0,22.0,101,162,2.0
9,Manacor,22,77,1201,447,754,476,1701,107,245,...,30.0,2038,167,189,906,44.0,27.0,148,188,2.4
10,Voley Textil Santanderina,22,75,1010,307,703,297,1488,70,202,...,24.0,2044,237,159,788,39.0,19.0,216,152,2.0
11,Rotogal Boiro,22,72,910,276,634,92,1390,69,239,...,29.0,1942,242,221,718,37.0,13.0,69,123,1.7

## Guardado en CSV.

In [16]:
result.to_csv('../../data/2022-2023/estadistica.csv', index=False)

## Base de datos.

In [4]:
with open('../../pass.txt', 'r') as file:   # pass.txt en .gitignore
    
    pass_ = file.read()

In [5]:
str_conn = f'mysql+pymysql://root:{pass_}@localhost:3306/'
conn = create_engine(str_conn)
engine = create_engine(f'mysql+pymysql://root:{pass_}@localhost:3306/volleyballdb')

In [6]:

estadistica.to_sql('estadisticas_temporada_anterior', engine, if_exists='append', index=False)

12