In [1]:
import sys
sys.path.append('C:\ironhack\Proyecto_final') # Hablar con el jefe
from src.funciones import scraping_opuesto
import pandas as pd

In [2]:
resultado = scraping_opuesto('https://www.rfevb.com/')

Scraping exitoso

In [3]:
resultado[3:20]

['Santos Cunha Bruno',
 '(Grupo Herce Soria)',
 '9',
 '35',
 '12',
 '24',
 '10',
 '146',
 '12',
 '23',
 '0',
 '56',
 '170',
 '23',
 '25',
 '369',
 '2,8286']

In [4]:
resultado = [resultado[i:i+18] for i in range(3, len(resultado), 18)]

opuesto = pd.DataFrame(resultado)
    
column_names = ['Nombre', 1, 'Partidos_jugados', 'Sets_jugados', 'Bloqueos', 'Bloqueo_exitoso',
                'Bloqueo_fallido', 'Total_bloqueos', 'Saque','Errores_Saque', 'Porcentaje_error',
                'Total_saques', 'Ataque_exitoso','Errores_ataque','Porcentaje_error','Total_ataques','Ataque_Ranking',17]

opuesto.columns = column_names
opuesto.drop(1, inplace=True, axis=1)
opuesto.drop(17, inplace=True, axis=1)
opuesto.drop(15, inplace=True)

In [5]:
opuesto

,Nombre,Partidos_jugados,Sets_jugados,Bloqueos,Bloqueo_exitoso,Bloqueo_fallido,Total_bloqueos,Saque,Errores_Saque,Porcentaje_error,Total_saques,Ataque_exitoso,Errores_ataque,Porcentaje_error,Total_ataques,Ataque_Ranking
0,Santos Cunha Bruno,9,35,12,24,10,146,12,23,0,56,170,23,25,369,"2,8286"
1,Neaves Matthew Michael,9,29,9,24,6,95,9,16,0,39,132,16,15,228,"2,7241"
2,Dahl Ulrik Bo,9,38,20,35,17,153,14,13,0,33,181,36,31,394,"2,6316"
3,Rodríguez Dosal Ángel,9,37,14,26,10,140,15,12,0,36,183,47,33,393,"2,5405"
4,Linares José Luis,9,33,12,26,7,108,7,6,0,20,158,32,30,328,"2,5152"
5,Martina Federico,9,29,3,2,2,61,4,7,0,18,86,5,9,168,"2,4138"
6,Nogueira Amorim Víctor Lucas,7,27,6,15,3,79,9,1,0,12,105,27,14,205,"2,3333"
7,Martínez Palacios Miguel Ángel,9,33,1,18,5,109,19,14,1,46,128,34,21,287,"1,8182"
8,Pereyra Hernán Federico,4,13,2,7,5,35,7,6,0,17,44,6,13,89,"1,6154"
9,Bezerra Souza Francisco Wallyson,8,25,10,20,4,80,6,11,0,23,68,7,15,150,"1,2400"
10,Dangel Mulen Armando,9,36,11,15,5,93,6,23,0,48,103,28,24,251,"0,8333"
11,Osorio Recordá Gerard,9,32,3,37,5,90,8,5,0,20,112,20,35,267,"0,8125"
12,Moreno Mosquera Juan Pablo,4,13,2,10,3,38,1,8,0,16,36,8,9,70,"0,3077"
13,Miranda de Alcantara Víctor Hugo,9,26,1,12,3,75,11,9,0,32,33,11,8,83,"0,1923"
14,Chourio González Anderson José,1,3,0,0,0,4,0,0,0,4,2,2,3,9,"-1,0000"

In [6]:
#Extraccion de jugadores.
df= pd.read_csv('..\..\data\Jugadores.csv')
df

,Unnamed: 0,Dorsal,Nombre,Posición,Año_de_nacimiento,id_jugador,id_equipo,Edad
0,0,2,Paradela Cortón Miguel,Líbero,2004,1,1,19
1,1,3,Bouza Ferreiro Víctor,Receptor,1990,2,1,33
2,2,4,Linares José Luis,Opuesto,1998,3,1,25
3,3,5,Barrasa Portomeñe Samuel,Líbero,2007,4,1,16
4,4,6,Edward Batalla Dexter,Colocador/a,2000,5,1,23
...,...,...,...,...,...,...,...,...
163,163,15,Marí Domene Álvaro,Middle-blocker,2002,164,12,21
164,164,17,Martínez Gómez Sergio,Opuesto,2002,165,12,21
165,165,20,Hernández Robeff Tomás Agustín,Receptor,1998,166,12,25
166,166,23,Jiménez Gallego Carlos,Receptor,1995,167,12,28
167,167,77,Fernández Rodríguez Francisco,Receptor,1996,168,12,27

In [7]:
opuesto = pd.merge(opuesto, df[['Nombre', 'id_jugador']], on='Nombre', how='left')

opuesto

,Nombre,Partidos_jugados,Sets_jugados,Bloqueos,Bloqueo_exitoso,Bloqueo_fallido,Total_bloqueos,Saque,Errores_Saque,Porcentaje_error,Total_saques,Ataque_exitoso,Errores_ataque,Porcentaje_error,Total_ataques,Ataque_Ranking,id_jugador
0,Santos Cunha Bruno,9,35,12,24,10,146,12,23,0,56,170,23,25,369,"2,8286",106
1,Neaves Matthew Michael,9,29,9,24,6,95,9,16,0,39,132,16,15,228,"2,7241",135
2,Dahl Ulrik Bo,9,38,20,35,17,153,14,13,0,33,181,36,31,394,"2,6316",92
3,Rodríguez Dosal Ángel,9,37,14,26,10,140,15,12,0,36,183,47,33,393,"2,5405",35
4,Linares José Luis,9,33,12,26,7,108,7,6,0,20,158,32,30,328,"2,5152",3
5,Martina Federico,9,29,3,2,2,61,4,7,0,18,86,5,9,168,"2,4138",81
6,Nogueira Amorim Víctor Lucas,7,27,6,15,3,79,9,1,0,12,105,27,14,205,"2,3333",25
7,Martínez Palacios Miguel Ángel,9,33,1,18,5,109,19,14,1,46,128,34,21,287,"1,8182",118
8,Pereyra Hernán Federico,4,13,2,7,5,35,7,6,0,17,44,6,13,89,"1,6154",78
9,Bezerra Souza Francisco Wallyson,8,25,10,20,4,80,6,11,0,23,68,7,15,150,"1,2400",58
10,Dangel Mulen Armando,9,36,11,15,5,93,6,23,0,48,103,28,24,251,"0,8333",149
11,Osorio Recordá Gerard,9,32,3,37,5,90,8,5,0,20,112,20,35,267,"0,8125",163
12,Moreno Mosquera Juan Pablo,4,13,2,10,3,38,1,8,0,16,36,8,9,70,"0,3077",62
13,Miranda de Alcantara Víctor Hugo,9,26,1,12,3,75,11,9,0,32,33,11,8,83,"0,1923",46
14,Chourio González Anderson José,1,3,0,0,0,4,0,0,0,4,2,2,3,9,"-1,0000",43

In [8]:
opuesto.to_csv('..\..\data/jugadores/opuesto.csv', index=False)