In [2]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import multiprocessing as mp
from joblib import Parallel, delayed
from selenium.webdriver.support.ui import Select
import time
import pandas as pd
from sqlalchemy import create_engine

In [3]:
opciones=Options()
opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.add_argument('--incognito')
opciones.add_argument('--start-maximized')

In [72]:
url = 'https://www.rfevb.com/competiciones/superliga-masculina'
driver = webdriver.Chrome(options = opciones)
driver.get(url)

In [73]:
# Click cookies
driver.find_element(By.XPATH , '//*[@id="lnkCookie"]').click()

In [74]:
# Entramos en plantilla
driver.find_element(By.XPATH , '//*[@id="miWrapper"]/ul/li[2]/ul/li[1]/a').click()

In [75]:
equipos = driver.find_elements(By.CLASS_NAME, 'rlvI')[0:12]
# Verificamos que los que nos devuelve son datos de mas entonces reiniciamos la lista con los elementos que nos interesa.

In [76]:
superLiga_Masculino=[]
for i in range(12):
    
    e = driver.find_elements(By.CLASS_NAME, 'rlvI')[i]
    
    print(e.text)
    
    e.click()
    
    print('Estoy dentro.')
    
    time.sleep(2)
   
    superLiga_Masculino.append(driver.find_elements(By.CLASS_NAME , 't-row')[3].text.split('\n'))
    
    print('Extraigo')
    
    time.sleep(2)
    
    driver.get('https://rfevb-web.dataproject.com/CompetitionTeamSearch.aspx?ID=124')
    
    time.sleep(2)

Arenal Emevé
Estoy dentro.
Extraigo
Cisneros Alter
Estoy dentro.
Extraigo
Club Vóley Palma
Estoy dentro.
Extraigo
Conectabalear CV Manacor
Estoy dentro.
Extraigo
CV Guaguas
Estoy dentro.
Extraigo
CV Melilla
Estoy dentro.
Extraigo
CV San Roque
Estoy dentro.
Extraigo
Grupo Herce Soria
Estoy dentro.
Extraigo
Pamesa Teruel Voleibol
Estoy dentro.
Extraigo
Unicaja Costa de Almería
Estoy dentro.
Extraigo
UPV Leleman Conqueridor
Estoy dentro.
Extraigo
Volei Villena Petrer
Estoy dentro.
Extraigo

In [10]:
superLiga_Masculino[0]

['#',
 'Nombre',
 'Posición',
 'Año de nacimiento',
 '2',
 'Paradela Cortón Miguel',
 'Líbero',
 '2004',
 '3',
 'Bouza Ferreiro Víctor',
 'Receptor',
 '1990',
 '4',
 'Linares José Luis',
 'Opuesto',
 '1998',
 '5',
 'Barrasa Portomeñe Samuel',
 'Líbero',
 '2007',
 '6',
 'Edward Batalla Dexter',
 'Colocador/a',
 '2000',
 '9',
 'Schulz Max',
 'Receptor',
 '2002',
 '10',
 'Biliato Luca',
 'Opuesto',
 '1993',
 '11',
 'Villar Álvarez Pablo',
 'Colocador/a',
 '2002',
 '12',
 'Rodríguez Rubio Aurelio',
 'Middle-blocker',
 '2000',
 '13',
 'Frías Collado Juan Francisco',
 'Middle-blocker',
 '2000',
 '14',
 'Augustinho De Lara Sopschuk Luis Henrique',
 'Middle-blocker',
 '2002',
 '17',
 'Ossola Gude Nahuel',
 'Receptor',
 '2002']

# Prueba

In [11]:
superLiga_Masculino[0][0:4]

['#', 'Nombre', 'Posición', 'Año de nacimiento']

In [12]:
superLiga_Masculino[0][4:]

['2',
 'Paradela Cortón Miguel',
 'Líbero',
 '2004',
 '3',
 'Bouza Ferreiro Víctor',
 'Receptor',
 '1990',
 '4',
 'Linares José Luis',
 'Opuesto',
 '1998',
 '5',
 'Barrasa Portomeñe Samuel',
 'Líbero',
 '2007',
 '6',
 'Edward Batalla Dexter',
 'Colocador/a',
 '2000',
 '9',
 'Schulz Max',
 'Receptor',
 '2002',
 '10',
 'Biliato Luca',
 'Opuesto',
 '1993',
 '11',
 'Villar Álvarez Pablo',
 'Colocador/a',
 '2002',
 '12',
 'Rodríguez Rubio Aurelio',
 'Middle-blocker',
 '2000',
 '13',
 'Frías Collado Juan Francisco',
 'Middle-blocker',
 '2000',
 '14',
 'Augustinho De Lara Sopschuk Luis Henrique',
 'Middle-blocker',
 '2002',
 '17',
 'Ossola Gude Nahuel',
 'Receptor',
 '2002']

In [13]:
# Definir las columnas y los datos
columns = superLiga_Masculino[0][0:4]
data = superLiga_Masculino[0][4:]

# Dividir los datos en lotes de 4 (ya que cada jugador tiene 4 atributos)
player_data = [data[i:i+4] for i in range(0, len(data), 4)]

# Crear el DataFrame
Arenal_Emeve = pd.DataFrame(player_data, columns=columns)

Arenal_Emeve = Arenal_Emeve.rename(columns={'#': 'Dorsal'})
Arenal_Emeve

,Dorsal,Nombre,Posición,Año de nacimiento
0,2,Paradela Cortón Miguel,Líbero,2004
1,3,Bouza Ferreiro Víctor,Receptor,1990
2,4,Linares José Luis,Opuesto,1998
3,5,Barrasa Portomeñe Samuel,Líbero,2007
4,6,Edward Batalla Dexter,Colocador/a,2000
5,9,Schulz Max,Receptor,2002
6,10,Biliato Luca,Opuesto,1993
7,11,Villar Álvarez Pablo,Colocador/a,2002
8,12,Rodríguez Rubio Aurelio,Middle-blocker,2000
9,13,Frías Collado Juan Francisco,Middle-blocker,2000
10,14,Augustinho De Lara Sopschuk Luis Henrique,Middle-blocker,2002
11,17,Ossola Gude Nahuel,Receptor,2002

# definimos DataFrame jugadores completo

In [41]:
Jugadores = pd.DataFrame()

# Iterar a través de las 12 sub-listas
for sublist in superLiga_Masculino:
    # Definir las columnas y los datos
    columns = sublist[0:4]
    data = sublist[4:]
    
    # Dividir los datos en lotes de 4 (ya que cada jugador tiene 4 atributos)
    player_data = [data[i:i+4] for i in range(0, len(data), 4)]
    
    # Crear un DataFrame temporal para esta sub-lista
    temp_df = pd.DataFrame(player_data, columns=columns)
    
    # Cambiar el nombre de la columna '#'
    temp_df = temp_df.rename(columns={'#': 'Dorsal'})
    
    # Concatenar el DataFrame temporal con el DataFrame principal
    Jugadores = pd.concat([Jugadores, temp_df], ignore_index=True)

# Mostrar el DataFrame final
Jugadores

    Dorsal                          Nombre        Posición Año de nacimiento
0        2          Paradela Cortón Miguel          Líbero              2004
1        3           Bouza Ferreiro Víctor        Receptor              1990
2        4               Linares José Luis         Opuesto              1998
3        5        Barrasa Portomeñe Samuel          Líbero              2007
4        6           Edward Batalla Dexter     Colocador/a              2000
..     ...                             ...             ...               ...
163     15              Marí Domene Álvaro  Middle-blocker              2002
164     17           Martínez Gómez Sergio         Opuesto              2002
165     20  Hernández Robeff Tomás Agustín        Receptor              1998
166     23          Jiménez Gallego Carlos        Receptor              1995
167     77   Fernández Rodríguez Francisco        Receptor              1996

[168 rows x 4 columns]

In [64]:
Jugadores['ID'] = Jugadores.index + 1
Jugadores

,Dorsal,Nombre,Posición,Año de nacimiento,ID
0,2,Paradela Cortón Miguel,Líbero,2004,1
1,3,Bouza Ferreiro Víctor,Receptor,1990,2
2,4,Linares José Luis,Opuesto,1998,3
3,5,Barrasa Portomeñe Samuel,Líbero,2007,4
4,6,Edward Batalla Dexter,Colocador/a,2000,5
...,...,...,...,...,...
163,15,Marí Domene Álvaro,Middle-blocker,2002,164
164,17,Martínez Gómez Sergio,Opuesto,2002,165
165,20,Hernández Robeff Tomás Agustín,Receptor,1998,166
166,23,Jiménez Gallego Carlos,Receptor,1995,167
167,77,Fernández Rodríguez Francisco,Receptor,1996,168

# pasamos este archivo a SQL.

In [6]:
with open('..\..\pass.txt', 'r') as file:   # pass.txt en .gitignore
    
    pass_ = file.read()

In [58]:
from sqlalchemy import create_engine

# Establece una conexión para crear la base de datos
str_conn = f'mysql+pymysql://root:{pass_}@localhost:3306/'
conn = create_engine(str_conn)

# Crea un motor para la base de datos FenixClub
engine = create_engine(f'mysql+pymysql://root:{pass_}@localhost:3306/FenixClub')

In [66]:
engine = create_engine(f'mysql+pymysql://root:{pass_}@localhost:3306/FenixClub')

In [60]:
Jugadores.to_sql('jugadores', con=engine, if_exists='replace', index=False)

In [ ]:
Jugadores.to_csv('Jugadores.csv', index=False)