In [1]:
import sys
sys.path.append('C:\ironhack\Proyecto_final') # Hablar con el jefe
from src.funciones import *
import pandas as pd

In [3]:
resultado = scraping_libero('https://www.rfevb.com/')

0
0

In [4]:
resultado = [resultado[i:i+13] for i in range(3, len(resultado), 13)]

libero = pd.DataFrame(resultado)

column_names = ['Nombre', 1, 'Partidos_jugados', 'Sets_jugados', 'Recepciones', 'Recepciones_exitosas',
                'Recepciones_fallidas', 'Recepciones_otro_jugador', 'Puntos_perdidos_recep',
                'Puntos_ganados_recep', 'Total_puntos_recep', 'Recep_Ranking', 12]

libero.columns = column_names
libero.drop(1, inplace=True, axis=1)
libero.drop(12, inplace=True, axis=1)
libero.drop(16, inplace=True)

In [6]:
libero.head()

,Nombre,Partidos_jugados,Sets_jugados,Recepciones,Recepciones_exitosas,Recepciones_fallidas,Recepciones_otro_jugador,Puntos_perdidos_recep,Puntos_ganados_recep,Total_puntos_recep,Recep_Ranking
0,San Martín Rodríguez Alejandro,5,17,28,3,6,0,7,16,60,"0,4167"
1,Masia Porres Arnau,9,31,109,18,1,11,25,51,215,"0,3721"
2,Almansa Jorge,1,3,8,0,2,1,2,9,22,"0,3182"
3,Barrasa Portomeñe Samuel,5,10,22,3,0,1,16,16,58,"0,3103"
4,Piris Guiscafré Antoni,9,30,73,12,5,7,32,51,180,"0,3000"

In [3]:
#Extraccion de jugadores.
df= pd.read_csv('..\..\data\Jugadores.csv')
df

,Unnamed: 0,Dorsal,Nombre,Posición,Año_de_nacimiento,id_jugador,id_equipo,Edad
0,0,2,Paradela Cortón Miguel,Líbero,2004,1,1,19
1,1,3,Bouza Ferreiro Víctor,Receptor,1990,2,1,33
2,2,4,Linares José Luis,Opuesto,1998,3,1,25
3,3,5,Barrasa Portomeñe Samuel,Líbero,2007,4,1,16
4,4,6,Edward Batalla Dexter,Colocador/a,2000,5,1,23
...,...,...,...,...,...,...,...,...
163,163,15,Marí Domene Álvaro,Middle-blocker,2002,164,12,21
164,164,17,Martínez Gómez Sergio,Opuesto,2002,165,12,21
165,165,20,Hernández Robeff Tomás Agustín,Receptor,1998,166,12,25
166,166,23,Jiménez Gallego Carlos,Receptor,1995,167,12,28
167,167,77,Fernández Rodríguez Francisco,Receptor,1996,168,12,27

In [130]:
liberos = pd.merge(libero, df[['Nombre', 'id_jugador']], on='Nombre', how='left')

liberos

,Nombre,Partidos_jugados,Sets_jugados,Recepciones,Recepciones_exitosas,Recepciones_fallidas,Recepciones_otro_jugador,Puntos_perdidos_recep,Puntos_ganados_recep,Total_puntos_recep,Recep_Ranking,id_jugador
0,San Martín Rodríguez Alejandro,5,17,28,3,6,0,7,16,60,"0,4167",102
1,Masia Porres Arnau,8,28,95,17,1,11,25,51,200,"0,3350",71
2,Almansa Jorge,1,3,8,0,2,1,2,9,22,"0,3182",61
3,Barrasa Portomeñe Samuel,4,8,17,2,0,1,12,13,45,"0,3111",4
4,Piqueres Flor Nestor,8,29,86,6,17,16,32,67,224,"0,2857",160
5,Piris Guiscafré Antoni,8,27,64,11,5,7,30,49,166,"0,2771",45
6,Dovale Fidalgo Mario,8,32,75,7,7,10,54,71,224,"0,2589",16
7,Paradela Cortón Miguel,8,24,54,10,7,7,32,38,148,"0,2500",1
8,Osado Carrasco José,8,32,65,12,13,8,18,72,188,"0,2394",34
9,Gallardo Hernández Rodrigo,8,33,62,10,14,11,36,41,174,"0,2356",90
10,Fernández Martínez Francisco José,8,26,47,13,6,2,35,38,141,"0,2270",132
11,Gámiz Padilla Aharón,8,31,53,6,10,10,29,57,165,"0,2242",125
12,Larrañaga Ledo Unai,7,26,46,11,4,8,16,44,129,"0,2093",60
13,Mengod Bautista Javier,8,30,39,13,31,9,41,51,184,"0,0924",152
14,Aulisi Santiago Karim,3,14,15,9,15,3,8,19,69,"0,0435",105
15,Iborra Ballester Héctor,3,10,3,6,9,2,8,9,37,"-0,1351",150

In [131]:
liberos.to_csv('data\jugadores\liberos.csv', index=False)

In [132]:
liberos

,Nombre,Partidos_jugados,Sets_jugados,Recepciones,Recepciones_exitosas,Recepciones_fallidas,Recepciones_otro_jugador,Puntos_perdidos_recep,Puntos_ganados_recep,Total_puntos_recep,Recep_Ranking,id_jugador
0,San Martín Rodríguez Alejandro,5,17,28,3,6,0,7,16,60,"0,4167",102
1,Masia Porres Arnau,8,28,95,17,1,11,25,51,200,"0,3350",71
2,Almansa Jorge,1,3,8,0,2,1,2,9,22,"0,3182",61
3,Barrasa Portomeñe Samuel,4,8,17,2,0,1,12,13,45,"0,3111",4
4,Piqueres Flor Nestor,8,29,86,6,17,16,32,67,224,"0,2857",160
5,Piris Guiscafré Antoni,8,27,64,11,5,7,30,49,166,"0,2771",45
6,Dovale Fidalgo Mario,8,32,75,7,7,10,54,71,224,"0,2589",16
7,Paradela Cortón Miguel,8,24,54,10,7,7,32,38,148,"0,2500",1
8,Osado Carrasco José,8,32,65,12,13,8,18,72,188,"0,2394",34
9,Gallardo Hernández Rodrigo,8,33,62,10,14,11,36,41,174,"0,2356",90
10,Fernández Martínez Francisco José,8,26,47,13,6,2,35,38,141,"0,2270",132
11,Gámiz Padilla Aharón,8,31,53,6,10,10,29,57,165,"0,2242",125
12,Larrañaga Ledo Unai,7,26,46,11,4,8,16,44,129,"0,2093",60
13,Mengod Bautista Javier,8,30,39,13,31,9,41,51,184,"0,0924",152
14,Aulisi Santiago Karim,3,14,15,9,15,3,8,19,69,"0,0435",105
15,Iborra Ballester Héctor,3,10,3,6,9,2,8,9,37,"-0,1351",150

# probar refactorizar el codigo con una funcion con len de columnas o input

In [ ]:
# Constantes
NUM_COLUMNAS = 27

def crear_dataframe_desde_trozos(datos, columnas):
    # Asumiendo que los datos son una lista
    trozos = [datos[i:i+NUM_COLUMNAS] for i in range(NUM_COLUMNAS, len(datos), NUM_COLUMNAS)]
    return pd.DataFrame(trozos, columns=columnas)

# Uso de la función
columnas = ['Equipo', 'Jugados', 'Sets_Jugados', 'Total_Puntos', 'Break_Puntos', 'Puntos_Ganados',
            'Puntos_Perdidos', 'Total_Saque', 'Puntos_Saque', 'Error_Saque', 'Puntos_por_set_Saque',
            'Efic_Saque', 'Total_Recepcion', 'Error_Recepcion', 'Negativo_Recepcion', 'Positivo_Recepcion',
            'Excelente_Recepcion', 'Efic_Recepcion', 'Total_Ataque', 'Error_Ataque', 'Ataque_Bloqueado',
            'Positivo_Ataque', 'Excelente_Ataque', 'Efic_Ataque', 'Toque_Red_Bloqueo', 'Puntos_de_Bloqueo',
            'Puntos_Set_Bloqueo']

estadistica = crear_dataframe_desde_trozos(resultado, columnas)