In [1]:
import sys
sys.path.append('C:\ironhack\Proyecto_final') # Hablar con el jefe
from src.help_scraping import *
from src.help_datos import *

In [2]:
url = 'https://rfevb-web.dataproject.com/Statistics.aspx?ID=82&PID=122'
parametro = 'estadistica_jugador'
datos = scraping(url,parametro)

hola
No se pudo hacer clic en el botón de cookies.
Scraping exitoso

In [5]:
columna = ['Nombre', 1, 'Partidos_jugados', 'Sets_jugados', 'Bloqueos', 'Bloqueo_exitoso',
                'Bloqueo_fallido', 'Total_bloqueos', 'Saque',
                'Errores_Saque', 'Porcentaje_error', 'Total_saques', 'Ataque_exitoso','Errores_ataque','Porc_error',
                'Total_ataques','Ataque_Ranking',2]

parametro= 'estadistica_central'

central = crear_df(datos[4],columna,parametro)
central.drop([1,2], inplace=True, axis=1)
central

,Nombre,Partidos_jugados,Sets_jugados,Bloqueos,Bloqueo_exitoso,Bloqueo_fallido,Total_bloqueos,Saque,Errores_Saque,Porcentaje_error,Total_saques,Ataque_exitoso,Errores_ataque,Porc_error,Total_ataques,Ataque_Ranking
0,Méndez Jiménez Víctor,23,86,67,18,0,105,4,30,11,271,182,18,13,273,"2,0233"
1,Enriquez Verdi José Manuel,22,76,54,27,0,89,9,22,5,241,115,9,12,235,"1,4211"
2,Ruiz Mira Borja,25,91,48,59,3,174,15,43,9,288,190,25,5,280,"1,2967"
3,De Carvalho Furtado Carlos Manuel,19,73,57,38,0,142,5,26,6,204,115,14,22,230,"1,0548"
4,Alzueta Joaquín,22,84,38,17,0,64,1,32,9,265,128,20,23,264,"0,8929"
5,En Nakhai Mohamed,18,48,17,5,0,23,5,24,8,142,77,17,13,162,"0,8333"

In [6]:
#Extraccion de jugadores.
df= pd.read_csv('../../data/2021-2022/jugadores.csv')
df.head(2)

,Dorsal,Nombre,Posición,Altura,Año_de_nacimiento,Alcance_en_ataque,Alcance_en_bloqueo,id_jugador,temporada,id_equipo
0,1,Alzueta Joaquín,Middle-blocker,196.0,2000,337.0,323.0,1-2021-2022,2021-2022,1-2021-2022
1,2,Paradela Cortón Miguel,Líbero,184.0,2004,310.0,305.0,2-2021-2022,2021-2022,1-2021-2022

In [7]:
central = pd.merge(central, df[['Nombre', 'id_jugador','id_equipo']], on='Nombre', how='left')
central['temporada']='2021-2022'
central

,Nombre,Partidos_jugados,Sets_jugados,Bloqueos,Bloqueo_exitoso,Bloqueo_fallido,Total_bloqueos,Saque,Errores_Saque,Porcentaje_error,Total_saques,Ataque_exitoso,Errores_ataque,Porc_error,Total_ataques,Ataque_Ranking,id_jugador,id_equipo,temporada
0,Méndez Jiménez Víctor,23,86,67,18,0,105,4,30,11,271,182,18,13,273,"2,0233",30-2021-2022,3-2021-2022,2022-2023
1,Enriquez Verdi José Manuel,22,76,54,27,0,89,9,22,5,241,115,9,12,235,"1,4211",70-2021-2022,6-2021-2022,2022-2023
2,Ruiz Mira Borja,25,91,48,59,3,174,15,43,9,288,190,25,5,280,"1,2967",50-2021-2022,4-2021-2022,2022-2023
3,De Carvalho Furtado Carlos Manuel,19,73,57,38,0,142,5,26,6,204,115,14,22,230,"1,0548",56-2021-2022,5-2021-2022,2022-2023
4,Alzueta Joaquín,22,84,38,17,0,64,1,32,9,265,128,20,23,264,"0,8929",1-2021-2022,1-2021-2022,2022-2023
5,En Nakhai Mohamed,18,48,17,5,0,23,5,24,8,142,77,17,13,162,"0,8333",146-2021-2022,11-2021-2022,2022-2023

In [8]:
convertir = central.columns.difference(['Nombre','id_jugador','id_equipo','temporada'])
central['Ataque_Ranking'] = central['Ataque_Ranking'].str.replace(',', '.').astype(float)
central[convertir] = central[convertir].applymap(lambda x: int(x) if str(x).isdigit() else x)
central.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nombre            6 non-null      object
 1   Partidos_jugados  6 non-null      int64
 2   Sets_jugados      6 non-null      int64
 3   Bloqueos          6 non-null      int64
 4   Bloqueo_exitoso   6 non-null      int64
 5   Bloqueo_fallido   6 non-null      int64
 6   Total_bloqueos    6 non-null      int64
 7   Saque             6 non-null      int64
 8   Errores_Saque     6 non-null      int64
 9   Porcentaje_error  6 non-null      int64
 10  Total_saques      6 non-null      int64
 11  Ataque_exitoso    6 non-null      int64
 12  Errores_ataque    6 non-null      int64
 13  Porc_error        6 non-null      int64
 14  Total_ataques     6 non-null      int64
 15  Ataque_Ranking    6 non-null      float64
 16  id_jugador        6 non-null      object
 17  id_equipo         6 non-null      object
 18  temporada         6 non-null      object
dtypes: float64(1), int64(14), object(4)
memory usage: 1.0+ KB

In [2]:
central=normalizar('../../data/2021-2022/central.csv')

## Guardado en CSV.

In [3]:
central.to_csv('../../data/2021-2022/central.csv', index=False)

## Base de datos.

In [3]:
with open('../../pass.txt', 'r') as file:   # pass.txt en .gitignore
    
    pass_ = file.read()

In [4]:
str_conn = f'mysql+pymysql://root:{pass_}@localhost:3306/'
conn = create_engine(str_conn)
engine = create_engine(f'mysql+pymysql://root:{pass_}@localhost:3306/volleyballdb')

In [5]:

central.to_sql('central', engine, if_exists='append', index=False)

6